import { useDeferredValue, useState } from 'react';
import { Link, useNavigate, useParams, useLocation } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { ApiError, api } from './api';
import { useAuth } from './auth';
import { priorities, statuses, type TaskItem, type TaskPage, type TaskStatus, type User } from './types';

const passwordSchema = z.string().min(8, 'Use at least 8 characters.');
const accountSchema = z.object({ name: z.string().trim().min(1, 'Name is required.').max(100, 'Name must be 100 characters or fewer.'), email: z.email('Enter a valid email address.'), password: passwordSchema });
const registerSchema = accountSchema.extend({ confirmPassword: z.string() }).refine(values => values.password === values.confirmPassword, { path: ['confirmPassword'], message: 'Passwords do not match.' });
type RegisterValues = z.infer<typeof registerSchema>;
const loginSchema = z.object({ email: z.email('Enter a valid email address.'), password: z.string().min(1, 'Password is required.') });
type LoginValues = z.infer<typeof loginSchema>;
const taskSchema = z.object({ title: z.string().trim().min(1, 'Title is required.').max(200, 'Title must be 200 characters or fewer.'), description: z.string().max(2000, 'Description must be 2000 characters or fewer.'), priority: z.enum(priorities) });
type TaskValues = z.infer<typeof taskSchema>;

function ErrorText({ message }: { message?: string }) { return message ? <span className="field-error">{message}</span> : null; }
function FormError({ error }: { error: unknown }) { return error ? <div className="alert alert-error" role="alert">{typeof error === 'string' ? error : error instanceof Error ? error.message : 'Something went wrong. Please try again.'}</div> : null; }
function AuthLayout({ title, subtitle, children, footer }: { title: string; subtitle: string; children: React.ReactNode; footer: React.ReactNode }) { return <div className="auth-page"><div className="auth-side"><Link className="brand brand-inverse" to="/login"><span className="brand-mark">A</span><span>anyware</span></Link><div className="auth-promo"><span className="eyebrow">MAKE ROOM FOR WHAT MATTERS</span><h1>Good work<br/>starts with<br/><em>a clear mind.</em></h1><p>A calmer place to turn your priorities into progress.</p></div><div className="auth-side-foot">TASK MANAGEMENT, MADE HUMAN</div></div><div className="auth-content"><div className="auth-card"><span className="eyebrow">WELCOME TO ANYWARE</span><h2>{title}</h2><p className="muted">{subtitle}</p>{children}<div className="auth-footer">{footer}</div></div></div></div>; }

export function Login() {
  const auth = useAuth(); const navigate = useNavigate(); const location = useLocation();
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<LoginValues>({ resolver: zodResolver(loginSchema) });
  const [serverError, setServerError] = useState('');
  const submit = async (data: LoginValues) => { setServerError(''); try { await auth.login(data); navigate((location.state as { from?: string } | null)?.from ?? '/tasks', { replace: true }); } catch (error) { setServerError(error instanceof Error ? error.message : 'Could not sign in.'); } };
  return <AuthLayout title="Welcome back" subtitle="Sign in to pick up where you left off." footer={<>New to Anyware? <Link to="/register">Create an account</Link></>}><form className="form-stack" onSubmit={handleSubmit(submit)} noValidate><FormError error={serverError || auth.message} /><label>Email address<input autoComplete="email" type="email" placeholder="you@example.com" {...register('email')}/><ErrorText message={errors.email?.message}/></label><label>Password<input autoComplete="current-password" type="password" placeholder="Your password" {...register('password')}/><ErrorText message={errors.password?.message}/></label><button className="button button-primary button-wide" disabled={isSubmitting}>{isSubmitting ? 'Signing in…' : 'Sign in'} <span>→</span></button></form></AuthLayout>;
}
export function Register() {
  const auth = useAuth(); const navigate = useNavigate();
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<RegisterValues>({ resolver: zodResolver(registerSchema) });
  const [serverError, setServerError] = useState('');
  const submit = async ({ confirmPassword: _confirmPassword, ...data }: RegisterValues) => { setServerError(''); try { await auth.register(data); navigate('/tasks', { replace: true }); } catch (error) { setServerError(error instanceof Error ? error.message : 'Could not create your account.'); } };
  return <AuthLayout title="Create your account" subtitle="Start with a little more clarity in your day." footer={<>Already have an account? <Link to="/login">Sign in</Link></>}><form className="form-stack" onSubmit={handleSubmit(submit)} noValidate><FormError error={serverError}/><label>Your name<input autoComplete="name" placeholder="Alex Morgan" {...register('name')}/><ErrorText message={errors.name?.message}/></label><label>Email address<input autoComplete="email" type="email" placeholder="you@example.com" {...register('email')}/><ErrorText message={errors.email?.message}/></label><label>Password<input autoComplete="new-password" type="password" placeholder="At least 8 characters" {...register('password')}/><ErrorText message={errors.password?.message}/></label><label>Confirm password<input autoComplete="new-password" type="password" placeholder="Enter it again" {...register('confirmPassword')}/><ErrorText message={errors.confirmPassword?.message}/></label><button className="button button-primary button-wide" disabled={isSubmitting}>{isSubmitting ? 'Creating account…' : 'Create account'} <span>→</span></button></form></AuthLayout>;
}

function PageHeading({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</div>; }
function TaskBadge({ kind, value }: { kind: 'status' | 'priority'; value: string }) { return <span className={`badge ${kind}-${value.toLowerCase()}`}>{kind === 'status' && <i/>}{value === 'InProgress' ? 'In progress' : value}</span>; }
function TaskCard({ task }: { task: TaskItem }) { return <Link className="task-card" to={`/tasks/${task.id}`}><div className="task-main"><div className="task-title-wrap"><span className="task-dot"/><h3>{task.title}</h3></div><p>{task.description || 'No description added.'}</p><div className="task-meta"><TaskBadge kind="status" value={task.status}/><TaskBadge kind="priority" value={task.priority}/><span className="date-text">Created {new Date(task.createdAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}</span></div></div><span className="task-arrow">↗</span></Link>; }
function TaskForm({ onCreated }: { onCreated: (task: TaskItem) => void }) {
  const { register, handleSubmit, reset, formState: { errors, isSubmitting } } = useForm<TaskValues>({ resolver: zodResolver(taskSchema), defaultValues: { title: '', description: '', priority: 'Medium' } });
  const [serverError, setServerError] = useState('');
  const submit = async (data: TaskValues) => { setServerError(''); try { const task = await api.createTask(data); reset({ title: '', description: '', priority: 'Medium' }); onCreated(task); } catch (error) { setServerError(error instanceof Error ? error.message : 'Could not create task.'); } };
  return <form className="create-form" onSubmit={handleSubmit(submit)} noValidate><div className="form-heading"><div><span className="eyebrow">NEW ITEM</span><h2>Create a task</h2></div><span className="form-mark">＋</span></div><FormError error={serverError}/><label>Task title<input maxLength={200} placeholder="What needs to get done?" {...register('title')}/><ErrorText message={errors.title?.message}/></label><label>Description <span className="optional">OPTIONAL</span><textarea maxLength={2000} rows={3} placeholder="Add a little context…" {...register('description')}/><ErrorText message={errors.description?.message}/></label><label>Priority<select {...register('priority')} >{priorities.map(priority => <option key={priority} value={priority}>{priority}</option>)}</select><ErrorText message={errors.priority?.message}/></label><button className="button button-primary button-wide" disabled={isSubmitting}>{isSubmitting ? 'Adding task…' : 'Add task'} <span>→</span></button></form>;
}
export function TaskList() {
  const client = useQueryClient();
  const [status, setStatus] = useState<'All' | TaskStatus>('All');
  const [search, setSearch] = useState('');
  const deferredSearch = useDeferredValue(search);
  const [page, setPage] = useState(1);
  const tasks = useQuery({ queryKey: ['tasks', page, status, deferredSearch], queryFn: () => api.listTasks(page, status, deferredSearch), refetchInterval: query => query.state.data?.items.some(task => task.status === 'Pending') ? 2500 : false, placeholderData: previous => previous });
  const pageItems = tasks.data?.items ?? [];
  const totalCount = tasks.data?.totalCount ?? 0;
  const totalPages = Math.max(1, Math.ceil(totalCount / 10));
  const noFilters = status === 'All' && deferredSearch.trim() === '';
  return <div className="content-grid"><section className="task-section"><PageHeading eyebrow="YOUR WORKSPACE" title="My tasks" description="A little progress adds up to a lot."/><div className="task-toolbar"><div className="filter-tabs">{(['All', ...statuses] as const).map(option => <button key={option} className={status === option ? 'filter active' : 'filter'} onClick={() => { setStatus(option); setPage(1); }}>{option === 'InProgress' ? 'In progress' : option}</button>)}</div><label className="search-box"><span>⌕</span><input aria-label="Search tasks by title" value={search} onChange={event => { setSearch(event.target.value); setPage(1); }} placeholder="Search tasks…"/></label></div>{tasks.isLoading ? <div className="panel state-panel"><span className="spinner"/><p>Gathering your tasks…</p></div> : tasks.isError ? <div className="panel state-panel"><span className="state-icon">!</span><h2>We couldn’t load your tasks</h2><p>{tasks.error.message}</p><button className="button button-outline" onClick={() => void tasks.refetch()}>Try again</button></div> : totalCount === 0 && noFilters ? <div className="panel empty-state"><span className="state-icon">✳</span><h2>You have no tasks yet</h2><p>Make space for your first bit of progress using the form.</p></div> : pageItems.length === 0 ? <div className="panel empty-state"><span className="state-icon">⌕</span><h2>No tasks match</h2><p>Try another title or change your filters.</p></div> : <div className="task-list">{pageItems.map(task => <TaskCard key={task.id} task={task}/>)}</div>}<div className="list-foot"><span>Showing <b>{pageItems.length}</b> of <b>{totalCount}</b> matching tasks</span><div className="pagination"><button className="button button-outline" onClick={() => setPage(current => Math.max(1, current - 1))} disabled={page <= 1}>← Previous</button><span>Page {page} of {totalPages}</span><button className="button button-outline" onClick={() => setPage(current => Math.min(totalPages, current + 1))} disabled={page >= totalPages}>Next →</button></div></div></section><aside><TaskForm onCreated={task => { setPage(1); setStatus('All'); setSearch(''); client.setQueryData<TaskPage>(['tasks', 1, 'All', ''], previous => previous ? { ...previous, items: [task, ...previous.items].sort((a, b) => priorities.indexOf(b.priority) - priorities.indexOf(a.priority) || a.createdAt.localeCompare(b.createdAt)).slice(0, 10), totalCount: previous.totalCount + 1 } : previous); void client.invalidateQueries({ queryKey: ['tasks'] }); }}/><div className="tip-card"><span className="tip-spark">✳</span><div><strong>One step at a time.</strong><p>Your tasks move forward in the background while you focus on what’s next.</p></div></div></aside></div>;
}

export function TaskDetail() {
  const { id = '' } = useParams(); const client = useQueryClient();
  const query = useQuery({ queryKey: ['task', id], queryFn: () => api.getTask(id), enabled: !!id, refetchInterval: current => current.state.data?.status === 'Pending' ? 2000 : false, retry: (count, error) => error instanceof ApiError && error.status === 404 ? false : count < 1 });
  const mutation = useMutation({ mutationFn: (status: TaskStatus) => api.updateTaskStatus(id, { status }), onSuccess: task => { client.setQueryData(['task', id], task); void client.invalidateQueries({ queryKey: ['tasks'] }); } });
  if (query.isLoading) return <div className="center-state"><span className="spinner"/>Loading task…</div>;
  if (query.error instanceof ApiError && query.error.status === 404) return <div className="panel state-panel"><span className="state-icon">⌑</span><h2>Task not found</h2><p>This task may have been removed or may not belong to your account.</p><Link className="button button-primary" to="/tasks">Back to my tasks</Link></div>;
  if (query.isError || !query.data) return <div className="panel state-panel"><h2>Couldn’t load task</h2><p>{query.error?.message ?? 'Task unavailable.'}</p><button className="button button-outline" onClick={() => void query.refetch()}>Try again</button></div>;
  const task = query.data;
  return <div className="detail-wrap"><Link className="back-link" to="/tasks">← Back to tasks</Link><article className="panel detail-panel"><div className="detail-top"><div><span className="eyebrow">TASK DETAILS</span><h1>{task.title}</h1></div><TaskBadge kind="status" value={task.status}/></div><p className="detail-description">{task.description || 'No description added.'}</p><div className="detail-facts"><div><span>PRIORITY</span><TaskBadge kind="priority" value={task.priority}/></div><div><span>CREATED</span><strong>{new Date(task.createdAt).toLocaleString()}</strong></div><div><span>TASK ID</span><code>{task.id}</code></div></div>{task.status === 'Pending' && <div className="processing-note"><span className="pulse-dot"/> Your task is being picked up in the background. This page updates automatically.</div>}<div className="status-control"><label htmlFor="task-status">Update status</label><select id="task-status" value={task.status} onChange={event => mutation.mutate(event.target.value as TaskStatus)} disabled={mutation.isPending}>{statuses.map(value => <option key={value} value={value}>{value === 'InProgress' ? 'In progress' : value}</option>)}</select>{mutation.isPending && <span className="muted">Saving…</span>}</div><FormError error={mutation.error}/></article></div>;
}

function UserForm() {
  const client = useQueryClient(); const { register, handleSubmit, reset, formState: { errors, isSubmitting } } = useForm<z.infer<typeof accountSchema>>({ resolver: zodResolver(accountSchema) });
  const [error, setError] = useState('');
  const submit = async (data: z.infer<typeof accountSchema>) => { setError(''); try { await api.createUser(data); reset(); await client.invalidateQueries({ queryKey: ['users'] }); } catch (e) { setError(e instanceof Error ? e.message : 'Could not create user.'); } };
  return <form className="create-form admin-form" onSubmit={handleSubmit(submit)} noValidate><div className="form-heading"><div><span className="eyebrow">ADD A TEAM MEMBER</span><h2>Create user</h2></div><span className="form-mark">＋</span></div><FormError error={error}/><label>Full name<input placeholder="Jamie Taylor" {...register('name')}/><ErrorText message={errors.name?.message}/></label><label>Email address<input type="email" placeholder="jamie@example.com" {...register('email')}/><ErrorText message={errors.email?.message}/></label><label>Temporary password<input type="password" placeholder="At least 8 characters" {...register('password')}/><ErrorText message={errors.password?.message}/></label><button className="button button-primary button-wide" disabled={isSubmitting}>{isSubmitting ? 'Creating…' : 'Create user'} <span>→</span></button></form>;
}
export function AdminUsers() {
  const query = useQuery({ queryKey: ['users'], queryFn: api.listUsers }); const client = useQueryClient(); const [selected, setSelected] = useState<User | null>(null); const [error, setError] = useState('');
  const deletion = useMutation({ mutationFn: (user: User) => api.deleteUser(user.id), onSuccess: async () => { setSelected(null); setError(''); await client.invalidateQueries({ queryKey: ['users'] }); }, onError: e => setError(e instanceof Error ? e.message : 'Could not delete user.') });
  return <div className="admin-layout"><section><PageHeading eyebrow="ADMINISTRATION" title="People" description="Manage the people who have access to Anyware."/><div className="panel users-panel"><div className="table-heading"><div><h2>All users</h2><span>{query.data?.length ?? 0} accounts</span></div><span className="eyebrow">USER DIRECTORY</span></div>{query.isLoading ? <div className="state-panel"><span className="spinner"/><p>Loading users…</p></div> : query.isError ? <div className="state-panel"><FormError error={query.error}/><button className="button button-outline" onClick={() => void query.refetch()}>Try again</button></div> : query.data?.length ? <div className="table-scroll"><table><thead><tr><th>NAME</th><th>EMAIL</th><th>ROLE</th><th>JOINED</th><th/></tr></thead><tbody>{query.data.map(user => <tr key={user.id}><td><span className="user-cell"><span className="avatar avatar-small">{user.name[0]?.toUpperCase()}</span><b>{user.name}</b></span></td><td>{user.email}</td><td><span className={`role-pill role-${user.role.toLowerCase()}`}>{user.role}</span></td><td>{new Date(user.createdAt).toLocaleDateString()}</td><td>{user.role !== 'Admin' && <button className="icon-button danger" title={`Delete ${user.name}`} aria-label={`Delete ${user.name}`} onClick={() => { setError(''); setSelected(user); }}>⌫</button>}</td></tr>)}</tbody></table></div> : <div className="empty-state"><h2>No users yet</h2><p>Add a user with the form.</p></div>}</div></section><aside><UserForm/><div className="tip-card"><span className="tip-spark">✦</span><div><strong>Keep access intentional.</strong><p>Users have their own private task lists. Only admins can manage this directory.</p></div></div></aside>{selected && <div className="modal-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget && !deletion.isPending) setSelected(null); }}><section className="confirm-modal" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><span className="modal-icon">⌫</span><span className="eyebrow">REMOVE USER</span><h2 id="confirm-title">Delete {selected.name}?</h2><p>This account will lose access to Anyware. Their tasks remain in the system.</p><FormError error={error}/><div className="modal-actions"><button className="button button-outline" onClick={() => setSelected(null)} disabled={deletion.isPending}>Cancel</button><button className="button button-danger" onClick={() => deletion.mutate(selected)} disabled={deletion.isPending}>{deletion.isPending ? 'Deleting…' : 'Delete user'}</button></div></section></div>}</div>;
}
export function NotFound() { const { user } = useAuth(); return <div className="not-found"><span className="eyebrow">404 / PAGE NOT FOUND</span><div className="not-found-number">404</div><h1>This path didn’t make it.</h1><p>The page you’re looking for has moved or never existed.</p><Link className="button button-primary" to={user ? '/tasks' : '/login'}>Go {user ? 'to my tasks' : 'to sign in'} <span>→</span></Link></div>; }
